import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const choose = await readFile(new URL('../app/choose/[client]/page.jsx', import.meta.url), 'utf8')
const dashboard = await readFile(new URL('../app/dashboard/page.jsx', import.meta.url), 'utf8')
const site = await readFile(new URL('../app/site/[client]/page.jsx', import.meta.url), 'utf8')
const theme = await readFile(new URL('../app/site/[client]/theme.module.css', import.meta.url), 'utf8')
const connect = await readFile(new URL('../../web/connect.html', import.meta.url), 'utf8')
const landing = await readFile(new URL('../../web/index.html', import.meta.url), 'utf8')

assert.match(choose, /Διαμόρφωσέ το με live chat/)
assert.match(choose, /select-design/)
assert.match(choose, /dashboard\?client=/)
assert.match(dashboard, /new URLSearchParams\(window\.location\.search\)\.get\('client'\)/)
assert.match(dashboard, /emailRedirectTo: destination/)
assert.match(dashboard, /redirectTo: destination/)
assert.match(choose, /sessionStorage\.setItem\('vitrina-active-client', client\)/)
assert.match(dashboard, /sessionStorage\.getItem\('vitrina-active-client'\)/)
assert.match(dashboard, /if \(fromUrl && !pick\)/)
assert.doesNotMatch(dashboard, /owned\.find\(\(c\) => c\.id === fromUrl\) \|\| owned\[0\]/)
assert.match(dashboard, /Επεξεργάζεσαι/)
assert.match(dashboard, /Επίλεξε site για επεξεργασία/)
assert.match(dashboard, /setPhotos\(null\)/)
assert.match(dashboard, /pendingClient\(\)/)
assert.match(dashboard, /palette/)
assert.match(dashboard, /font_pair/)
assert.match(dashboard, /assetType = 'photo'/)
assert.match(dashboard, /asset_type', staged\.assetType/)
assert.match(dashboard, /Ανέβασε λογότυπο/)
assert.match(dashboard, /asset\.type === 'logo'/)
assert.match(dashboard, /logo-drafts/)
assert.match(choose, /3 προτάσεις λογοτύπου/)
assert.match(landing, /Logo Designer περιλαμβάνεται/)
assert.match(landing, /σου ετοιμάζουμε 3 προτάσεις/)
assert.match(landing, /connect\.html\?desc=/)
assert.match(connect, /Βήμα 2 — Συμπλήρωσε τα στοιχεία του μαγαζιού/)
assert.match(connect, /Δείξε μου τα σχέδια →/)
for (const businessType of ['Φαρμακείο', 'Γιατρός / Ιατρείο', 'Νύχια / Nail studio',
  'Κέντρο αισθητικής', 'Μασάζ / Wellness', 'Κατάστημα λιανικής',
  'Ενοικιαζόμενα δωμάτια', 'Συνεργείο αυτοκινήτων']) {
  assert.match(connect, new RegExp(`<option>${businessType.replace('/', '\\/')}</option>`))
}
assert.match(choose, /dashboard\?client=/)
assert.match(dashboard, /Δημιούργησε 3 προτάσεις/)
assert.match(dashboard, /Χρησιμοποίησέ το/)
assert.match(site, /data-palette=/)
assert.match(site, /data-font=/)
assert.match(site, /siteData\.palette \|\| siteData\.PALETTE/)
assert.match(site, /siteData\.font_pair \|\| siteData\.FONT_PAIR/)
assert.match(theme, /data-palette='forest'/)
assert.match(theme, /data-font='friendly'/)
assert.match(connect, /query\.has\('code'\)/)
assert.match(connect, /hash\.has\('access_token'\)/)
assert.match(connect, /sites-production-da56\.up\.railway\.app\/dashboard/)

console.log('editorFlow: theme selection -> live editor -> palette and typography preview passed')
